copyright = "© Lythriel"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "term"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "Europe/Berlin"
timeout = "120s"
title = "Gallery"

[params]
  defaultTheme = "dark"
  description = "A website for sharing photography works."
  title = "My Gallery"
  [params.author]
    email = "llzy21@qq.com"
    name = "Lythriel"
  [params.socialIcons]
    #facebook = "https://www.facebook.com/"
    #instagram = "https://www.instagram.com/"
    #github = "https://github.com/"
    #youtube = "https://www.youtube.com/"
    email = "mailto:llzy21@qq.com"
    fivehpx = "https://500px.com.cn/Llzy21"
    #website = "https://example.com"
    #mastodon = "https://example.com"
    #pixelfed = "https://example.com"
    tiktok = "https://www.douyin.com/user/MS4wLjABAAAABptCD0OTPV5okRGo_Lef6IK7DkpJRiBlUQyZddyub5c"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[menu]
  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/zL219/gallery"
    weight = 3

[services]
  [services.rss]
    limit = 100
